version: "3.8"

volumes:
  postgres_data:
  static_data:

services:

  db:
    image: postgres:12.4-alpine
    restart: always
    container_name: POSTGRESQLDOCKER
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
#    command: /bin/bash ./bin/prod.sh
    image: alexxdockerhub/yamdb_app:latest
    container_name: APIDOCKER
    restart: always
    volumes:
      - static_data:/code/static
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
#    build: ./nginx
    image: nginx
    container_name: APINGINX
    restart: always
    volumes:
      - ./api.conf:/etc/nginx/conf.d
#      - ./api.conf:/etc/nginx/conf.d/default.conf
      - static_data:/code/static
    ports:
      - "80:80"
    depends_on:
      - web