version: '3.8'

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:12.4-alpine
    container_name: POSTGRESQLDOCKER
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: alexxdockerhub/yamdb_app:latest
    container_name: APIDOCKER
    restart: always
    command: /bin/bash ./bin/dev.sh
    volumes:
      - static_data:/code/static
      - media_data:/code/media
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
      image: nginx:1.19.3
      container_name: APINGINX
      ports:
        - "80:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - static_data:/code/static
        - media_data:/code/media
      depends_on:
        - web